name: cutnrun
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - ant
  - bioconda::bioconductor-genomicranges
  - bioconda::bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconda::bioconductor-regioner
  - bowtie2
  - bedops
  - bedtools
  - meme
  - bzip2
  - numpy
  - curl
  - cairo
  - deeptools
  - fastqc
  - git
  - macs3
  - matplotlib
  - nextflow
  - openjdk
  - pcre
  - picard
  - pip
  - plotly
  - python
  - r-base
  - r-biocmanager
  - r-cowplot
  - r-devtools
  - r-drc
  - r-gert
  - r-ggnewscale
  - r-ggplot2
  - r-ggplotify
  - r-ggrepel
  - r-ggsci
  - r-grid
  - r-gridextra
  - r-magrittr
  - r-nloptr
  - r-regioner
  - r-tictoc
  - r-tidyverse
  - samtools
  - scipy
  - tree
  - trim-galore
